### ISSUE TITLE
SM1.9 Fix ?

### ISSUE THREAD

**Issue by P4R4DiSi4C** [rogeraabbccdd/Kento-Rankme#1] opened 2016-11-05 13:21 UTC
Hello !
I saw you didn't support SM 1.9.
Do you think to release a fix soon ?

Thank you so much

**Comment by rogeraabbccdd** [comment] 2016-11-05 14:01
I didn't test my plugin in SM1.9, this bug is reported by Nachtfrische in [this post](https://forums.alliedmods.net/showpost.php?p=2467450&postcount=1247).

Btw, I'm using SM1.8.0-5947 in my server.

**Comment by VirtualHeaven** [comment] 2016-11-14 18:36
I'm running on SM 1.9 without any problems, only one issue with the rankme db being reset after mapchange (using mysql), otherwise everything works just fine for me

**Comment by rogeraabbccdd** [comment] 2016-11-15 12:33
Thanks for your feedback, I'll checking mysql problem.

**Comment by rogeraabbccdd** [comment] 2016-11-15 16:21
@VirtualHeaven Do you have any error log?

**Comment by Nachtfrische** [comment] 2016-11-15 17:38
Hey,

as I've mentioned in the thread [here](https://forums.alliedmods.net/showpost.php?p=2464722&postcount=1233), I'm having the same problem as VirtualHeaven. It works fine on 1.9 but the points are not saved after a Mapchange. I'm using MySQL as well.

Error logs are:
`L 11/02/2016 - 23:45:09: [SM] Exception reported: Instruction contained invalid parameter
L 11/02/2016 - 23:45:09: [SM] Blaming: rankme_kento.smx
L 11/02/2016 - 23:45:09: [SM] Call stack trace:
L 11/02/2016 - 23:45:09: [SM]   [1] Line 1221, C:\Program Files (x86)\Steam\SteamApps\common\csgo plug\sourcemod-1.7.3-git5280-windows\addons\sourcemod\scripting\rankme_kento.sp::Event_RoundEnd`

and

`L 11/03/2016 - 23:53:14: [SM] Exception reported: Instruction contained invalid parameter
L 11/03/2016 - 23:53:14: [SM] Blaming: rankme_kento.smx
L 11/03/2016 - 23:53:14: [SM] Call stack trace:
L 11/03/2016 - 23:53:14: [SM]   [1] Line 1221, rankme_kento.sp::Event_RoundEnd`

I'll be willing to try and test any new test version under 1.9. Thanks.

**Comment by rogeraabbccdd** [comment] 2016-11-15 18:24
Confirmed, 3.0.3.Kento.3 is also not working in SM1.9.
In fact, I'm not planning to update this plugin for SM1.9 before it become stable.

**Comment by Nachtfrische** [comment] 2016-11-15 23:32
I know that SM1.9 is a dev build but is it really so much trouble to fix it now? You are going to have to fix it at some point, it shouldn't matter if you fix it now or if you fix it in 6 months.

**Comment by bcart22** [comment] 2016-12-01 05:15
Alot of people, including myself, had to switch to 1.9 because of the last CSGO update 11/28/16. I know it's not stable, but I would really appreciate a working patch for this. If you can do it, hope you take it into consideration. Thank you so much!

**Comment by rogeraabbccdd** [comment] 2016-12-01 07:13
Unfortunately, I'm still using SM1.8 after glove update. (1.8-5961)

**Comment by TR1D** [comment] 2016-12-01 10:26
All fixes are introduced in 1.8

**Comment by peace-maker** [comment] 2016-12-11 09:30
It's because of the ridiculously long `Format` call in `SalvarPlayer` with 37 arguments. You need to rethink your table layout or split the string up into multiple smaller Format calls to get it to run in SM1.9.
SM1.9 enforces calls to obey the maximal argument count of 32 arguments. There's a mismatch in the allowed argument count between the compiler and the VM which's fix [is pending](https://bugs.alliedmods.net/show_bug.cgi?id=6540).

Just stopping by 😉

**Comment by rogeraabbccdd** [comment] 2016-12-11 10:13
What the...
I hope SM1.9 can fix this asap, I'm too lazy to rethink the tables. _(:з」∠)_

**Comment by rogeraabbccdd** [comment] 2017-01-11 10:28
Fixed In 3.0.3.Kento.18 .

**Closed by rogeraabbccdd** 2017-01-11 10:28 UTC
